### ISSUE TITLE
Will you support crossbrowser?

### ISSUE THREAD

**Issue by Muskos** [bsidelinger912/shiitake#18]
Well done on ie.
But in mozilla. I write  lines={2}. The result is one line.
In chrome, when line-height is difference then font-size, i saw only half part of text.
Also some times all looks good after resize.

**Comment by bsidelinger912** [comment]
Hey @Muskos, thanks for using Shiitake.  I'm not seeing the issues your seeing. I tested with firefox 57.0.1 and can create a two line instance just fine with my test page.  In chrome, not related to shiitake at all, making line height different can cut off text if the line height is less than the text.  I've got a fiddle here: https://codepen.io/bsidelinger912/pen/xpxVXY that shows the text looks the same in shiitake and without shiitake.  Feel free to fork and update the codepen to capture a more specific repro scenario.
