### ISSUE TITLE
Improve performance on initial load

### ISSUE THREAD

**Issue by thomasthesecond** [bsidelinger912/shiitake#2]
This module works really well, but I'm noticing a slight lag before the clamped content appears, illustrated below:

![line-clamp](https://cloud.githubusercontent.com/assets/1479563/16668778/02b0a528-4458-11e6-8185-d4aeae41f917.gif)

I have 10 items per page that are getting clamped. Could that be contributing to the issue?

Also, I have the `throttleRate` set to `100`, but not sure if that affects the initial load.

What can be done to speed it up, or maybe even display the content (and hiding overflow via CSS) before clamping?

**Comment by bsidelinger912** [comment]
Hi @thomasthesecond, I've experienced the same thing on initial load.  One idea I had was while we're calculating the initial content we could put the whole string in there and set a fixed height on the element  with overlfow:hidden.  I'll play with that tonight and update when I've got something.

**Comment by thomasthesecond** [comment]
Cool, yeah that's exactly what I was thinking of.

**Comment by bsidelinger912** [comment]
I've got a good start here: https://github.com/bsidelinger912/shiitake/tree/improve-initial-load.  I just need to test it and clean it up.

**Comment by bsidelinger912** [comment]
#3 Merged, using binary search for max string length on initial load as well as showing full string with overflow: hidden.

**Comment by bsidelinger912** [comment]
@thomasthesecond, I've just released v1.0.2 and it's got the actual build from the pull request I mentioned above.  I don't have CI set up for this project (yet apparently) so I forgot to build previously.  I pulled it into our big app at work and it's pretty darn fast now, I hope it works for you!

**Comment by thomasthesecond** [comment]
Awesome, thanks for that. I look forward to trying it out!
