### ISSUE TITLE
How to know if the text is truncated ?

### ISSUE THREAD

**Issue by bahaa-al-deen** [bsidelinger912/shiitake#26]
First of all, let me thank you for the great component (you saved me a lot of time).

I was wondering if there's a supported way to determine if shiitake truncated it's children or not. (without messing around with the DOM)

I tried taking a ref and looking at the state. found allChildren, testChildren but it didn't help much.

**Comment by bsidelinger912** [comment]
Hey @bahaa-al-deen, this is basically the same ask as with #25.  I can see the need for this for sure, so I'll work on a solution ASAP.

**Comment by bsidelinger912** [comment]
This release should give you what you need @bahaa-al-deen: https://github.com/bsidelinger912/shiitake/releases/tag/v2.3.0

**Comment by bahaa-al-deen** [comment]
thanks
