### ISSUE TITLE
add custom params

### ISSUE THREAD

**Issue by StipJey** [bsidelinger912/shiitake#29]
For example, I would like to add the "title" property

**Comment by bsidelinger912** [comment]
@StipJey this makes total sense, I'll work on some support.  Just to clarify though, you want to add title to the tag we wrap around the target, correct?  This would essentially be a tooltip for screen readers and such I'd imagine.  If you actually want it to be applied to the tooltip itself, let me know as that's a different use case altogether (which is ok too, but want to be clear).

**Comment by bsidelinger912** [comment]
I believe this is addressed now with https://github.com/bsidelinger912/shiitake/releases/tag/v3.0.0.
