### ISSUE TITLE
Remove 'componentWillReceiveProps' for React 17

### ISSUE THREAD

**Issue by zioth** [bsidelinger912/shiitake#32]
`componentWillReceiveProps` and the other `will` lifecycle events are deprecated, and support will be removed soon. Please either remove the need for these events, or switch to the `UNSAFE_` versions.

Thanks!

**Comment by bsidelinger912** [comment]
@zioth looking closer this is best done by switching to hooks and cleaning up some of the old logic. I'm working on that and plan on addressing this with a MV that requires react 16.8+ as a peer dependency.  I'll let you know when it's out.

**Comment by zioth** [comment]
Sounds great. Thanks!

**Comment by bsidelinger912** [comment]
Finally got this done @zioth, see: https://github.com/bsidelinger912/shiitake/releases/tag/v3.0.0.

**Comment by zioth** [comment]
Thank you! I look forward to trying out the new version.
