### ISSUE TITLE
Can be "a" in the tag whitelist?

### ISSUE THREAD

**Issue by ycanales** [bsidelinger912/shiitake#34]
Would the truncation work? Thanks!

**Comment by bsidelinger912** [comment]
hey @ycanales the only issue I see with this is that I don't pass arbitrary props into the wrapper tag, so you wouldn't be able to add an href.  I do pass events in though so maybe that's all your needing?  I'm considering passing more props along, but there's some potential drawbacks I'm thinking about how to mitigate.

**Comment by bsidelinger912** [comment]
@ycanales I just added in v3 as well as a new prop called "attributes" where you can pass additional attributes like "href".  See here for details: https://github.com/bsidelinger912/shiitake/releases/tag/v3.0.0.

**Comment by ycanales** [comment]
@bsidelinger912 thanks a lot!
