### ISSUE TITLE
classes for span...

### ISSUE THREAD

**Issue by wilmanh** [bsidelinger912/shiitake#35]
hi i just wondering if you can add a className for the span children that you create for clamp...

thanks!

**Comment by bsidelinger912** [comment]
Hey @wilmanh I'm working on a new branch to get rid of componentWillRecieveProps and am planning on adding a fixed classname to the span that wraps the truncated children "shiitake-children".  Given that you can pass a className to the outerMost element you could do .my-class .shiitake-children { ...whatever }.  Would that fit your needs?

**Comment by bsidelinger912** [comment]
@wilmanh I've added those two inner classes and will close the issue, please open another one if this doesn't solve your use case.
