### ISSUE TITLE
[3.0] Typescript: attributes property should be optional

### ISSUE THREAD

**Issue by dgomez-orangeloops** [bsidelinger912/shiitake#41]
@bsidelinger912 

`  export interface ShiitakeProps {
    lines: number,
    throttleRate?: number,
    className?: string,
    tagName?: string,
    overflowNode?: React.ReactNode,
    onTruncationChange?: (isTruncated: boolean) => void,
    **attributes: WhitelistedElementAttributes,**
  }`

**Comment by bsidelinger912** [comment]
Ugh, my bad.  Just published a patch.
