### ISSUE TITLE
Updating UI state does not result in a change of value rendered

### ISSUE THREAD

**Issue by berziiii** [bsidelinger912/shiitake#42]
We are using v3.0.1 within a react app. When we have a state change with this version, the value in which is wrapped in the Shiitake component does not update without a resize event. Therefore, when the UI needs to change, it holds onto the old value and just appends a ... instead of re-rendering the component to determine if the new value needs to be truncated or not. 

The value appears to be appended to the DOM but the original value does not update. This is not an issue in v2.3.1

![image](https://user-images.githubusercontent.com/8379295/71742488-f3fce800-2e2f-11ea-9821-4b24a9389f95.png)

Work around is to add a `key={stateValue}` to trigger a re-render of the component so when the value in the state changes, the component will adjust

**Comment by bsidelinger912** [comment]
Hi @berziiii this should be fixed now with v3.0.2.

**Comment by bsidelinger912** [comment]
Closing as I believe this was fixed some time ago
