### ISSUE TITLE
set lines dynamically

### ISSUE THREAD

**Issue by mangakid** [bsidelinger912/shiitake#7]
Hi @bsidelinger912 I would like to be able to set the lines dynamically, depending on state. But can't seem to get this to work. It only registers the change when the window is resized. Example: http://codepen.io/mangakid/pen/LxmdjR

**Comment by bsidelinger912** [comment]
Hi @mangakid, I'm working on this currently.  I'll let you know when it's done.

**Comment by bsidelinger912** [comment]
Ok @mangakid, the latest version 1.4.0 is available and allows for dynamic changing of the "lines" prop.  Let me know how it works for you.

**Comment by bsidelinger912** [comment]
@mangakid I believe this is working as expected, you can clone the repo and run `npm run dev` to check out a demo.   Closing the issue as it's done.
