### ISSUE TITLE
Which commit is pointing to 1.3.0 release on npm?

### ISSUE THREAD

**Issue by tugberkugurlu** [bsidelinger912/shiitake#8]
> First of all, thanks for putting this library out for others to use. It's really helpful 👍 

I can see that there is 1.3.0 version of this package available [on npm](https://www.npmjs.com/package/shiitake):

![image](https://cloud.githubusercontent.com/assets/328122/23266675/585805be-f9e0-11e6-936e-4d351485a059.png)

However, I cannot see which commit that is pointing to. This is the latest commit I can find but it's for 1.2.0: https://github.com/bsidelinger912/shiitake/commit/d8702787af80485e7f58cadba223f55553c8934d

As a general feedback, it would be nice to tag the releases.

**Comment by bsidelinger912** [comment]
@tugberkugurlu, it looks like I forgot to push my last two commits.  I just pushed and you can see the latest commit on master is tagged with v1.3.0: https://github.com/bsidelinger912/shiitake/commit/2090c1031fb3f04090713d6816f57c5dd4e1a02d.  Thanks for pointing this out!
